"""increase panelist_id length to 50

Revision ID: 03db9756f08e
Revises: 20343d10539e
Create Date: 2026-01-27 15:04:41.118464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03db9756f08e'
down_revision: Union[str, Sequence[str], None] = '20343d10539e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('panelists', 'id',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('study_responses', 'panelist_id',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.String(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('study_responses', 'panelist_id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=8),
               existing_nullable=True)
    op.alter_column('panelists', 'id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False)
    # ### end Alembic commands ###
