"""verify_migration

Revision ID: 09d9552265f8
Revises: 2a1f13df102f
Create Date: 2026-01-26 09:03:45.077325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09d9552265f8'
down_revision: Union[str, Sequence[str], None] = '2a1f13df102f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('studies', sa.Column('toggle_shuffle', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('studies', 'toggle_shuffle')
    # ### end Alembic commands ###
