"""added indexing

Revision ID: 487aca99dfb8
Revises: c139e862ee94
Create Date: 2025-09-14 14:47:05.265287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '487aca99dfb8'
down_revision: Union[str, Sequence[str], None] = 'c139e862ee94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_completed_task_analytics', 'completed_tasks', ['study_response_id', 'task_duration_seconds'], unique=False)
    op.create_index('idx_element_interaction_analytics', 'element_interactions', ['study_response_id', 'element_id'], unique=False)
    op.create_index('idx_study_response_analytics', 'study_responses', ['study_id', 'is_completed', 'is_abandoned'], unique=False)
    op.create_index('idx_study_response_duration', 'study_responses', ['study_id', 'total_study_duration'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_study_response_duration', table_name='study_responses')
    op.drop_index('idx_study_response_analytics', table_name='study_responses')
    op.drop_index('idx_element_interaction_analytics', table_name='element_interactions')
    op.drop_index('idx_completed_task_analytics', table_name='completed_tasks')
    # ### end Alembic commands ###
