"""new migration

Revision ID: 572cebb2f20d
Revises: 6fbd7dbce8fa
Create Date: 2025-10-13 15:10:55.492076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '572cebb2f20d'
down_revision: Union[str, Sequence[str], None] = '6fbd7dbce8fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('studies', sa.Column('background_image_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('studies', 'background_image_url')
    # ### end Alembic commands ###
