"""remove_username_column

Revision ID: 5f3834fe0402
Revises: 572cebb2f20d
Create Date: 2025-10-25 16:59:05.123650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f3834fe0402'
down_revision: Union[str, Sequence[str], None] = '572cebb2f20d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_user_username_active'), table_name='users')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_constraint(op.f('uq_user_username'), 'users', type_='unique')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('uq_user_username'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_index(op.f('idx_user_username_active'), 'users', ['username', 'is_active'], unique=False)
    # ### end Alembic commands ###
