"""Change element_id to UUID type

Revision ID: 6fbd7dbce8fa
Revises: b863edc7e69e
Create Date: 2025-10-09 23:16:34.193002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fbd7dbce8fa'
down_revision: Union[str, Sequence[str], None] = 'b863edc7e69e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # First, clear existing data since we're changing the column type
    op.execute("DELETE FROM study_elements")
    
    # Use raw SQL to change the column type with proper USING clause
    op.execute("ALTER TABLE study_elements ALTER COLUMN element_id TYPE UUID USING element_id::uuid")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('study_elements', 'element_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    # ### end Alembic commands ###
