"""add share model

Revision ID: 722284316a53
Revises: 67cc4b526198
Create Date: 2026-01-07 12:02:18.131711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '722284316a53'
down_revision: Union[str, Sequence[str], None] = '67cc4b526198'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('study_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('study_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('role', sa.Enum('admin', 'editor', 'viewer', name='study_role_enum'), server_default='viewer', nullable=False),
    sa.Column('invited_email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['study_id'], ['studies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('study_id', 'invited_email', name='uq_study_members_study_email')
    )
    op.create_index('idx_study_members_study_id_role', 'study_members', ['study_id', 'role'], unique=False)
    op.create_index('idx_study_members_user_id', 'study_members', ['user_id'], unique=False)
    op.create_index(op.f('ix_study_members_invited_email'), 'study_members', ['invited_email'], unique=False)
    op.create_index(op.f('ix_study_members_study_id'), 'study_members', ['study_id'], unique=False)
    op.create_index(op.f('ix_study_members_user_id'), 'study_members', ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(op.f('ix_study_members_user_id'), table_name='study_members')
    op.drop_index(op.f('ix_study_members_study_id'), table_name='study_members')
    op.drop_index(op.f('ix_study_members_invited_email'), table_name='study_members')
    op.drop_index('idx_study_members_user_id', table_name='study_members')
    op.drop_index('idx_study_members_study_id_role', table_name='study_members')
    op.drop_table('study_members')
    # ### end Alembic commands ###
