"""added status

Revision ID: 7c4f63fdfd16
Revises: 487aca99dfb8
Create Date: 2025-09-14 17:40:02.589175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c4f63fdfd16'
down_revision: Union[str, Sequence[str], None] = '487aca99dfb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study_responses', sa.Column('status', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_study_responses_status'), 'study_responses', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_study_responses_status'), table_name='study_responses')
    op.drop_column('study_responses', 'status')
    # ### end Alembic commands ###
