"""added response model

Revision ID: 8c24a811457c
Revises: a7e4fcf7f6da
Create Date: 2025-09-07 22:48:07.034615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8c24a811457c'
down_revision: Union[str, Sequence[str], None] = 'a7e4fcf7f6da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('study_responses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('study_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.String(length=50), nullable=False),
    sa.Column('respondent_id', sa.Integer(), nullable=False),
    sa.Column('current_task_index', sa.Integer(), nullable=True),
    sa.Column('completed_tasks_count', sa.Integer(), nullable=True),
    sa.Column('total_tasks_assigned', sa.Integer(), nullable=False),
    sa.Column('session_start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('session_end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('personal_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('browser_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('completion_percentage', sa.Float(), nullable=True),
    sa.Column('total_study_duration', sa.Float(), nullable=True),
    sa.Column('last_activity', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_abandoned', sa.Boolean(), nullable=True),
    sa.Column('abandonment_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('abandonment_reason', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['study_id'], ['studies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_study_response_abandoned', 'study_responses', ['is_abandoned'], unique=False)
    op.create_index('idx_study_response_activity', 'study_responses', ['last_activity'], unique=False)
    op.create_index('idx_study_response_completed', 'study_responses', ['is_completed'], unique=False)
    op.create_index('idx_study_response_respondent', 'study_responses', ['respondent_id'], unique=False)
    op.create_index('idx_study_response_session', 'study_responses', ['session_id'], unique=False)
    op.create_index('idx_study_response_start_time', 'study_responses', ['session_start_time'], unique=False)
    op.create_index('idx_study_response_study', 'study_responses', ['study_id'], unique=False)
    op.create_index(op.f('ix_study_responses_id'), 'study_responses', ['id'], unique=False)
    op.create_index(op.f('ix_study_responses_session_id'), 'study_responses', ['session_id'], unique=True)
    op.create_index(op.f('ix_study_responses_study_id'), 'study_responses', ['study_id'], unique=False)
    op.create_table('classification_answers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('study_response_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.String(length=10), nullable=False),
    sa.Column('question_text', sa.String(length=500), nullable=False),
    sa.Column('answer', sa.String(length=1000), nullable=False),
    sa.Column('answer_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('time_spent_seconds', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['study_response_id'], ['study_responses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_classification_question', 'classification_answers', ['question_id'], unique=False)
    op.create_index('idx_classification_response', 'classification_answers', ['study_response_id'], unique=False)
    op.create_index(op.f('ix_classification_answers_id'), 'classification_answers', ['id'], unique=False)
    op.create_index(op.f('ix_classification_answers_study_response_id'), 'classification_answers', ['study_response_id'], unique=False)
    op.create_table('completed_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('study_response_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.String(length=20), nullable=False),
    sa.Column('respondent_id', sa.Integer(), nullable=False),
    sa.Column('task_index', sa.Integer(), nullable=False),
    sa.Column('elements_shown_in_task', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('elements_shown_content', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('task_type', sa.String(length=50), nullable=True),
    sa.Column('task_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('task_start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('task_completion_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('task_duration_seconds', sa.Float(), nullable=False),
    sa.Column('rating_given', sa.Integer(), nullable=False),
    sa.Column('rating_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('elements_shown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('layers_shown_in_task', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['study_response_id'], ['study_responses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_completed_task_id', 'completed_tasks', ['task_id'], unique=False)
    op.create_index('idx_completed_task_respondent', 'completed_tasks', ['respondent_id'], unique=False)
    op.create_index('idx_completed_task_response', 'completed_tasks', ['study_response_id'], unique=False)
    op.create_index(op.f('ix_completed_tasks_id'), 'completed_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_completed_tasks_study_response_id'), 'completed_tasks', ['study_response_id'], unique=False)
    op.create_table('task_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.String(length=50), nullable=False),
    sa.Column('task_id', sa.String(length=20), nullable=False),
    sa.Column('study_response_id', sa.UUID(), nullable=False),
    sa.Column('classification_page_time', sa.Float(), nullable=True),
    sa.Column('orientation_page_time', sa.Float(), nullable=True),
    sa.Column('individual_task_page_times', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('page_transitions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('abandonment_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('abandonment_reason', sa.String(length=200), nullable=True),
    sa.Column('recovery_attempts', sa.Integer(), nullable=True),
    sa.Column('browser_performance', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('page_load_times', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('device_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('screen_resolution', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['study_response_id'], ['study_responses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_task_session_completed', 'task_sessions', ['is_completed'], unique=False)
    op.create_index('idx_task_session_created', 'task_sessions', ['created_at'], unique=False)
    op.create_index('idx_task_session_response', 'task_sessions', ['study_response_id'], unique=False)
    op.create_index('idx_task_session_session', 'task_sessions', ['session_id'], unique=False)
    op.create_index('idx_task_session_task', 'task_sessions', ['task_id'], unique=False)
    op.create_index(op.f('ix_task_sessions_id'), 'task_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_task_sessions_session_id'), 'task_sessions', ['session_id'], unique=False)
    op.create_index(op.f('ix_task_sessions_study_response_id'), 'task_sessions', ['study_response_id'], unique=False)
    op.create_index(op.f('ix_task_sessions_task_id'), 'task_sessions', ['task_id'], unique=False)
    op.create_table('element_interactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('study_response_id', sa.UUID(), nullable=False),
    sa.Column('task_session_id', sa.UUID(), nullable=True),
    sa.Column('element_id', sa.String(length=10), nullable=False),
    sa.Column('view_time_seconds', sa.Float(), nullable=False),
    sa.Column('hover_count', sa.Integer(), nullable=True),
    sa.Column('click_count', sa.Integer(), nullable=True),
    sa.Column('first_view_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_view_time', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['study_response_id'], ['study_responses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_session_id'], ['task_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_element_interaction_element', 'element_interactions', ['element_id'], unique=False)
    op.create_index('idx_element_interaction_response', 'element_interactions', ['study_response_id'], unique=False)
    op.create_index('idx_element_interaction_task', 'element_interactions', ['task_session_id'], unique=False)
    op.create_index(op.f('ix_element_interactions_id'), 'element_interactions', ['id'], unique=False)
    op.create_index(op.f('ix_element_interactions_study_response_id'), 'element_interactions', ['study_response_id'], unique=False)
    op.create_index(op.f('ix_element_interactions_task_session_id'), 'element_interactions', ['task_session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_element_interactions_task_session_id'), table_name='element_interactions')
    op.drop_index(op.f('ix_element_interactions_study_response_id'), table_name='element_interactions')
    op.drop_index(op.f('ix_element_interactions_id'), table_name='element_interactions')
    op.drop_index('idx_element_interaction_task', table_name='element_interactions')
    op.drop_index('idx_element_interaction_response', table_name='element_interactions')
    op.drop_index('idx_element_interaction_element', table_name='element_interactions')
    op.drop_table('element_interactions')
    op.drop_index(op.f('ix_task_sessions_task_id'), table_name='task_sessions')
    op.drop_index(op.f('ix_task_sessions_study_response_id'), table_name='task_sessions')
    op.drop_index(op.f('ix_task_sessions_session_id'), table_name='task_sessions')
    op.drop_index(op.f('ix_task_sessions_id'), table_name='task_sessions')
    op.drop_index('idx_task_session_task', table_name='task_sessions')
    op.drop_index('idx_task_session_session', table_name='task_sessions')
    op.drop_index('idx_task_session_response', table_name='task_sessions')
    op.drop_index('idx_task_session_created', table_name='task_sessions')
    op.drop_index('idx_task_session_completed', table_name='task_sessions')
    op.drop_table('task_sessions')
    op.drop_index(op.f('ix_completed_tasks_study_response_id'), table_name='completed_tasks')
    op.drop_index(op.f('ix_completed_tasks_id'), table_name='completed_tasks')
    op.drop_index('idx_completed_task_response', table_name='completed_tasks')
    op.drop_index('idx_completed_task_respondent', table_name='completed_tasks')
    op.drop_index('idx_completed_task_id', table_name='completed_tasks')
    op.drop_table('completed_tasks')
    op.drop_index(op.f('ix_classification_answers_study_response_id'), table_name='classification_answers')
    op.drop_index(op.f('ix_classification_answers_id'), table_name='classification_answers')
    op.drop_index('idx_classification_response', table_name='classification_answers')
    op.drop_index('idx_classification_question', table_name='classification_answers')
    op.drop_table('classification_answers')
    op.drop_index(op.f('ix_study_responses_study_id'), table_name='study_responses')
    op.drop_index(op.f('ix_study_responses_session_id'), table_name='study_responses')
    op.drop_index(op.f('ix_study_responses_id'), table_name='study_responses')
    op.drop_index('idx_study_response_study', table_name='study_responses')
    op.drop_index('idx_study_response_start_time', table_name='study_responses')
    op.drop_index('idx_study_response_session', table_name='study_responses')
    op.drop_index('idx_study_response_respondent', table_name='study_responses')
    op.drop_index('idx_study_response_completed', table_name='study_responses')
    op.drop_index('idx_study_response_activity', table_name='study_responses')
    op.drop_index('idx_study_response_abandoned', table_name='study_responses')
    op.drop_table('study_responses')
    # ### end Alembic commands ###
