"""add_product_id_to_study_responses

Revision ID: 9584902e5a2f
Revises: d94e29bd296e
Create Date: 2026-01-25 17:29:16.480965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9584902e5a2f'
down_revision: Union[str, Sequence[str], None] = 'd94e29bd296e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study_responses', sa.Column('product_id', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('study_responses', 'product_id')
    # ### end Alembic commands ###
