"""added_panelist_id

Revision ID: a53d24ddf2dc
Revises: 356662f2d050
Create Date: 2026-01-25 19:58:17.702926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a53d24ddf2dc'
down_revision: Union[str, Sequence[str], None] = '356662f2d050'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('panelists',
    sa.Column('id', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=50), nullable=True),
    sa.Column('creator_email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['creator_email'], ['users.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_panelist_creator', 'panelists', ['creator_email'], unique=False)
    op.create_index('idx_panelist_search', 'panelists', ['id', 'name'], unique=False)
    op.create_index(op.f('ix_panelists_creator_email'), 'panelists', ['creator_email'], unique=False)
    op.add_column('study_responses', sa.Column('panelist_id', sa.String(length=10), nullable=True))
    op.create_index(op.f('ix_study_responses_panelist_id'), 'study_responses', ['panelist_id'], unique=False)
    op.create_foreign_key(None, 'study_responses', 'panelists', ['panelist_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'study_responses', type_='foreignkey')
    op.drop_index(op.f('ix_study_responses_panelist_id'), table_name='study_responses')
    op.drop_column('study_responses', 'panelist_id')
    op.drop_index(op.f('ix_panelists_creator_email'), table_name='panelists')
    op.drop_index('idx_panelist_search', table_name='panelists')
    op.drop_index('idx_panelist_creator', table_name='panelists')
    op.drop_table('panelists')
    # ### end Alembic commands ###
