"""added study model

Revision ID: a7e4fcf7f6da
Revises: 088e2e06876e
Create Date: 2025-09-07 18:17:13.760289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a7e4fcf7f6da'
down_revision: Union[str, Sequence[str], None] = '088e2e06876e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('studies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('background', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=10), server_default='en', nullable=False),
    sa.Column('main_question', sa.Text(), nullable=False),
    sa.Column('orientation_text', sa.Text(), nullable=False),
    sa.Column('study_type', sa.Enum('grid', 'layer', name='study_type_enum'), nullable=False),
    sa.Column('rating_scale', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('iped_parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tasks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('creator_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'paused', 'completed', name='study_status_enum'), server_default='draft', nullable=False),
    sa.Column('share_token', sa.String(length=255), nullable=False),
    sa.Column('share_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('launched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_responses', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('completed_responses', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('abandoned_responses', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('share_token', name='uq_studies_share_token')
    )
    op.create_index('idx_studies_creator_status_created_at', 'studies', ['creator_id', 'status', 'created_at'], unique=False)
    op.create_index('idx_studies_status_created_at', 'studies', ['status', 'created_at'], unique=False)
    op.create_index('idx_studies_study_type', 'studies', ['study_type'], unique=False)
    op.create_index(op.f('ix_studies_creator_id'), 'studies', ['creator_id'], unique=False)
    op.create_index(op.f('ix_studies_id'), 'studies', ['id'], unique=False)
    op.create_index(op.f('ix_studies_share_token'), 'studies', ['share_token'], unique=True)
    op.create_table('study_elements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('study_id', sa.UUID(), nullable=False),
    sa.Column('element_id', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('element_type', sa.Enum('image', 'text', name='element_type_enum'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('alt_text', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['study_id'], ['studies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('study_id', 'element_id', name='uq_study_elements_element_id')
    )
    op.create_index('idx_study_elements_study_id_element_id', 'study_elements', ['study_id', 'element_id'], unique=False)
    op.create_index(op.f('ix_study_elements_study_id'), 'study_elements', ['study_id'], unique=False)
    op.create_table('study_layers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('study_id', sa.UUID(), nullable=False),
    sa.Column('layer_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('z_index', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['study_id'], ['studies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('study_id', 'layer_id', name='uq_study_layers_layer_id')
    )
    op.create_index('idx_study_layers_study_id_layer_id', 'study_layers', ['study_id', 'layer_id'], unique=False)
    op.create_index(op.f('ix_study_layers_study_id'), 'study_layers', ['study_id'], unique=False)
    op.create_table('layer_images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('layer_id', sa.UUID(), nullable=False),
    sa.Column('image_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('alt_text', sa.String(length=200), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['layer_id'], ['study_layers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('layer_id', 'image_id', name='uq_layer_images_image_id')
    )
    op.create_index('idx_layer_images_layer_id_image_id', 'layer_images', ['layer_id', 'image_id'], unique=False)
    op.create_index(op.f('ix_layer_images_layer_id'), 'layer_images', ['layer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_layer_images_layer_id'), table_name='layer_images')
    op.drop_index('idx_layer_images_layer_id_image_id', table_name='layer_images')
    op.drop_table('layer_images')
    op.drop_index(op.f('ix_study_layers_study_id'), table_name='study_layers')
    op.drop_index('idx_study_layers_study_id_layer_id', table_name='study_layers')
    op.drop_table('study_layers')
    op.drop_index(op.f('ix_study_elements_study_id'), table_name='study_elements')
    op.drop_index('idx_study_elements_study_id_element_id', table_name='study_elements')
    op.drop_table('study_elements')
    op.drop_index(op.f('ix_studies_share_token'), table_name='studies')
    op.drop_index(op.f('ix_studies_id'), table_name='studies')
    op.drop_index(op.f('ix_studies_creator_id'), table_name='studies')
    op.drop_index('idx_studies_study_type', table_name='studies')
    op.drop_index('idx_studies_status_created_at', table_name='studies')
    op.drop_index('idx_studies_creator_status_created_at', table_name='studies')
    op.drop_table('studies')
    # ### end Alembic commands ###
