"""add study step

Revision ID: aa8d9c944d32
Revises: e90a63782b08
Create Date: 2025-11-25 09:46:59.931183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa8d9c944d32'
down_revision: Union[str, Sequence[str], None] = 'e90a63782b08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('studies', sa.Column('last_step', sa.Integer(), server_default=sa.text('1'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('studies', 'last_step')
    # ### end Alembic commands ###
