"""added classification question

Revision ID: c139e862ee94
Revises: 0a537a8d0492
Create Date: 2025-09-12 11:04:47.876884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c139e862ee94'
down_revision: Union[str, Sequence[str], None] = '0a537a8d0492'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('study_classification_questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('study_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.String(length=10), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('question_type', sa.String(length=20), nullable=False),
    sa.Column('is_required', sa.String(length=1), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('answer_options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['study_id'], ['studies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('study_id', 'question_id', name='uq_study_classification_questions_question_id')
    )
    op.create_index('idx_study_classification_questions_study_id_order', 'study_classification_questions', ['study_id', 'order'], unique=False)
    op.create_index(op.f('ix_study_classification_questions_study_id'), 'study_classification_questions', ['study_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_study_classification_questions_study_id'), table_name='study_classification_questions')
    op.drop_index('idx_study_classification_questions_study_id_order', table_name='study_classification_questions')
    op.drop_table('study_classification_questions')
    # ### end Alembic commands ###
