"""add_project_model

Revision ID: d3dc3da15957
Revises: 5e6ba6549895
Create Date: 2026-02-04 18:37:48.325788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3dc3da15957'
down_revision: Union[str, Sequence[str], None] = '5e6ba6549895'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('creator_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_projects_creator_id_created_at', 'projects', ['creator_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_projects_creator_id'), 'projects', ['creator_id'], unique=False)
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.add_column('studies', sa.Column('project_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_studies_project_id'), 'studies', ['project_id'], unique=False)
    op.create_foreign_key(None, 'studies', 'projects', ['project_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'studies', type_='foreignkey')
    op.drop_index(op.f('ix_studies_project_id'), table_name='studies')
    op.drop_column('studies', 'project_id')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_creator_id'), table_name='projects')
    op.drop_index('idx_projects_creator_id_created_at', table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
