"""added clou_id

Revision ID: d7435a4c47d0
Revises: f0e8e41d1816
Create Date: 2025-09-08 16:00:32.921345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7435a4c47d0'
down_revision: Union[str, Sequence[str], None] = 'f0e8e41d1816'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('layer_images', sa.Column('cloudinary_public_id', sa.Text(), nullable=True))
    op.add_column('study_elements', sa.Column('cloudinary_public_id', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('study_elements', 'cloudinary_public_id')
    op.drop_column('layer_images', 'cloudinary_public_id')
    # ### end Alembic commands ###
