"""added hubrid

Revision ID: f6a4fb30dc26
Revises: 722284316a53
Create Date: 2026-01-23 11:21:43.803692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f6a4fb30dc26'
down_revision: Union[str, Sequence[str], None] = '722284316a53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('studies', sa.Column('phase_order', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('study_categories', sa.Column('phase_type', sa.Enum('grid', 'layer', 'text', 'hybrid', name='study_type_enum'), nullable=True))
    op.alter_column('study_elements', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=1000),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('study_elements', 'name',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('study_categories', 'phase_type')
    op.drop_column('studies', 'phase_order')
    # ### end Alembic commands ###
