"""add user_optimizations table

Revision ID: fec53fdfc29b
Revises: aa8d9c944d32
Create Date: 2025-11-25 20:18:29.303841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fec53fdfc29b'
down_revision: Union[str, Sequence[str], None] = 'aa8d9c944d32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('studies', sa.Column('jobid', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_studies_jobid'), 'studies', ['jobid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_studies_jobid'), table_name='studies')
    op.drop_column('studies', 'jobid')
    # ### end Alembic commands ###
